### ISSUE TITLE
Fix config bugs

### ISSUE THREAD

**Issue by aaprasad** [talmolab/biogtr#15]
There are a couple parameters missing from the config which leads to `train.py` erroring. It's a pretty easy fix, we just need to edit [`config.py` line 234](https://github.com/talmolab/biogtr/blob/e30a6b59e32e88716be3cba02662028976fb2fde/biogtr/config.py#L234) to 
```
logger_params = OmegaConf.to_container(self.cfg.logging, resolve=True)
```

and then edit `base.yaml` to add the following:
```
logging:
      logger_type: null
      
view_batch:
    enable: false
    no_train: false
```
